INSERT INTO HOSTEL_DIRECTORY(ROOM_NO,SID,S_NAME,S_CITY) VALUES (1022,33,'Tyler','Jackson');
INSERT INTO HOSTEL_DIRECTORY(ROOM_NO,SID,S_NAME,S_CITY) VALUES (1023,33,'Trisha','Starkville');
INSERT INTO HOSTEL_DIRECTORY(ROOM_NO,SID,S_NAME,S_CITY) VALUES (1024,33,'Ava','Jackson');